%YAML:1.0
# Oxford Newer College 2021 Collection-3 Alphasense IMU calibration.
imu_preintegration_type: 1

T_BS:
  cols: 4
  rows: 4
  data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]
rate_hz: 200

imu_bias_init_sigma: 1e-3
gyroscope_noise_density: 0.019
gyroscope_random_walk: 0.000266
accelerometer_noise_density: 0.019
accelerometer_random_walk: 0.0043

do_imu_rate_time_alignment: 0
time_alignment_window_size_s: 10.0
time_alignment_variance_threshold_scaling: 30.0
imu_integration_sigma: 1.0e-8
imu_time_shift: 0.0017891047954595573
n_gravity: [0.0, 0.0, -9.81]
